name: finding_path
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  grid_repository:
    path: packages/grid_repository

  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true